# Устранение проблем с подключением к {{ ydb-short-name }} из кода функции {{ sf-name }}


## Описание проблемы {#issue-description}

После создания новой ревизии функции {{ sf-name }} и при ее последующем вызове перестало устанавливаться соединение к {{ ydb-short-name }}.

## Решение {#issue-resolution}

В новых версиях {{ ydb-short-name }} SDK требуется явно передавать токен авторизации. В более ранних версиях {{ ydb-short-name }} SDK этого требования не было.

Добавьте в `requirements.txt` строку `ydb==2.13.3`, создайте еще одну ревизию функции, вызовите функцию повторно и проверьте успешность подключения к {{ ydb-short-name }}.

## Если проблема осталась {#if-issue-still-persists}

Если вышеописанные действия не помогли решить проблему, [создайте запрос в техническую поддержку]({{ link-console-support }}). При создании запроса укажите следующую информацию:

1. Идентификатор облачной функции.
1. Полный текст сообщения об ошибке из лога функции в результате попытки подключения к {{ ydb-short-name }}.
